spring:
  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/analyzer
    username: analyzer_user
    password: analyzer_password

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  sql:
    init:
      mode: always

kafka:
  snapshot-config:
    group-id: analyzer-snapshot-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: ru.yandex.practicum.kafka.deserializer.SensorSnapshotDeserializer
    enable-auto-commit: false
    bootstrap-servers: ${spring.kafka.bootstrap-servers}
    topic: telemetry.snapshots.v1

  hub-event-config:
    group-id: analyzer-hub-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
    enable-auto-commit: true
    auto-commit-interval-ms: 5000
    bootstrap-servers: ${spring.kafka.bootstrap-servers}
    topic: telemetry.hubs.v1

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

server:
  port: 8083